apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ecom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-ecom-app
  template:
    metadata:
      labels:
        app: demo-ecom-app
    spec:
      containers:
      - name: demo-ecom-app
        image: sarveshanand94/ecomdb:v4
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: '3'
            memory: 3000Mi
          requests:
            cpu: '3'
            memory: 3000Mi
        envFrom:
          - configMapRef:
              name: demo-ecom-db-config
---
apiVersion: v1
kind: Service
metadata:
  name: demo-ecom-app-service
spec:
  selector:
    app: demo-ecom-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer  # This exposes the service publicly
